### ISSUE TITLE
Example XML lacks correct spacing on older activity and organisation standard pages (v2.02, v2.01, etc.)

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#758]
**Brief Description**

I noticed that for [org>recipient-country-budget](https://iatistandard.org/en/iati-standard/203/organisation-standard/iati-organisations/iati-organisation/recipient-country-budget/) elements, the example XML seems to run the element and attribute together with no space, for some reason:

![Firefox_Screenshot_2023-12-12T16-13-23 599Z](https://github.com/IATI/IATI-Extra-Documentation/assets/1209944/96e40c44-73b4-4aec-8326-164fa7e3136f)

This also seems to be the case on [recipient-region-budget](https://iatistandard.org/en/iati-standard/203/organisation-standard/iati-organisations/iati-organisation/recipient-region-budget/) , [recipient-org-budget](https://iatistandard.org/en/iati-standard/203/organisation-standard/iati-organisations/iati-organisation/recipient-org-budget/) and it fact all elements for the org standard

I don't see similar behaviour on the activity standard docs though - eg [budget](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/budget/):

![Firefox_Screenshot_2023-12-12T16-16-59 610Z](https://github.com/IATI/IATI-Extra-Documentation/assets/1209944/d1af42ec-124b-4568-ad83-682b13b82f87)

I don't also see any issue with the [example XML](https://github.com/IATI/IATI-Extra-Documentation/blob/version-2.03/en/organisation-standard/organisation-standard-example-annotated.xml) itself, from which these snippets are referenced

Hence - unclear what is happening here

**Severity**
Medium

**Issue Location**

https://iatistandard.org/en/iati-standard/203/organisation-standard/

**Steps to Reproduce**

Visit https://iatistandard.org/en/iati-standard/203/organisation-standard/ and navigate to element pages
Check the Example XML that is printed

**Expected Results/Behaviour**

I would expect a character space between elements and attributes, in the example XML print

**Actual Results/Behaviour**

On the org standard, the example XML seems to somehow remove the space between elements and attributes, in many pages

Checked on Ubuntu, using both Firefox and Chrome

**Comment by Bjwebb** [comment]
Looks to me like this does affect the activity standard as well, which I think is shown in your budget example.

**Comment by Bjwebb** [comment]
Looks like this is a problem with how [Reference-Generator](https://github.com/IATI/IATI-Reference-Generator) rewrites the most recent sphinx output. Unfortunately because not all requirements are pinned, it's not easy to rollback.

I think I've identified the change that's needs to be made in the reference generator code though:  https://github.com/IATI/IATI-Reference-Generator/pull/116

And, I've deployed this fix to dev: https://dev.iatistandard.org/en/iati-standard/203/organisation-standard/iati-organisations/iati-organisation/recipient-country-budget/
That looks fixed to me, @stevieflow could you confirm? (And maybe have a click around to check nothing else is broken instead.)

If everything's okay, I can put this live later in the week.

**Comment by stevieflow** [comment]
Thanks @Bjwebb 

It certainly now looks fixed

![Firefox_Screenshot_2023-12-13T13-31-06 584Z](https://github.com/IATI/IATI-Extra-Documentation/assets/1209944/185a037f-f30a-4d3a-ae32-58f9b3218aa2)

One thing I notice if I compare to the [activity standard docs](https://dev.iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/budget/) is that the formatting seems a little different:

![Firefox_Screenshot_2023-12-13T13-31-17 747Z](https://github.com/IATI/IATI-Extra-Documentation/assets/1209944/d50ee22f-4e18-4ce1-afba-c63667f079a3)

Whilst it could be argued that the activity docs are more "colorful", they don't seem quite right (eg highlighting ``date`` in a different shade

**Comment by Bjwebb** [comment]
I've rolled the change out to live.

I'll create a new issue for that formatting inconsistency, as I agree it's wrong for `iso-date`.

**Comment by emmajclegg** [comment]
Reopening this as a record that the problem still exists on some older page versions of the Standard - e.g.

- v 2.02 - [activity budget](https://iatistandard.org/en/iati-standard/202/activity-standard/iati-activities/iati-activity/budget/) 
<img width="490" height="200" alt="Image" src="https://github.com/user-attachments/assets/3b476b6f-dcbe-44f6-8b41-32dcb92356c9" />

- v 2.02 - [organisation recipient-country-budget](https://iatistandard.org/en/iati-standard/202/organisation-standard/iati-organisations/iati-organisation/recipient-country-budget/)

<img width="600" height="225" alt="Image" src="https://github.com/user-attachments/assets/39911576-2402-401c-bd93-1acde25d6a72" />


Pages for v 2.03 of the Standard all look ok.
